// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-QewSxWN4v8Po6-ZAShWJOpl7dFVteVc',
    appId: '1:567877689943:web:1b09fba834d746608cf912',
    messagingSenderId: '567877689943',
    projectId: 'apk-perjalanan-dinas',
    authDomain: 'apk-perjalanan-dinas.firebaseapp.com',
    storageBucket: 'apk-perjalanan-dinas.firebasestorage.app',
    measurementId: 'G-GRGXG35K9J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDX-MkHqy8GghqLNsxOKEY_GKdFpWKwCPs',
    appId: '1:567877689943:android:29bedc62a0d9e7f58cf912',
    messagingSenderId: '567877689943',
    projectId: 'apk-perjalanan-dinas',
    storageBucket: 'apk-perjalanan-dinas.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4eYNu56JJ1a5ATJQIbBcT0reVPw3FLvs',
    appId: '1:567877689943:ios:af2a369ab1510de58cf912',
    messagingSenderId: '567877689943',
    projectId: 'apk-perjalanan-dinas',
    storageBucket: 'apk-perjalanan-dinas.firebasestorage.app',
    iosBundleId: 'com.example.tripsApps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4eYNu56JJ1a5ATJQIbBcT0reVPw3FLvs',
    appId: '1:567877689943:ios:af2a369ab1510de58cf912',
    messagingSenderId: '567877689943',
    projectId: 'apk-perjalanan-dinas',
    storageBucket: 'apk-perjalanan-dinas.firebasestorage.app',
    iosBundleId: 'com.example.tripsApps',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-QewSxWN4v8Po6-ZAShWJOpl7dFVteVc',
    appId: '1:567877689943:web:139e9ca2ff8185738cf912',
    messagingSenderId: '567877689943',
    projectId: 'apk-perjalanan-dinas',
    authDomain: 'apk-perjalanan-dinas.firebaseapp.com',
    storageBucket: 'apk-perjalanan-dinas.firebasestorage.app',
    measurementId: 'G-CXY01H8HWE',
  );
}
